name: muslim
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  # Dépendances pour les appels API HTTP
  http: ^1.2.2

  # Dépendance pour la gestion des fichiers locaux (par exemple, JSON)
  flutter_localizations:
    sdk: flutter

  # Gestion des fichiers locaux (pour charger JSON, etc.)
  #path_provider: ^2.1.5

  # Dépendances pour la gestion des notifications locales
  flutter_local_notifications: ^18.0.1

  # Dépendances pour la gestion des icônes personnalisées dans l'application
  font_awesome_flutter: ^10.8.0

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/core/json/
    - assets/images/core/svg/
    - assets/images/error/lottie_json/
    - assets/images/navigation_icon/svg/
    - assets/images/home_icon/svg/
    - assets/images/home_icon/lottie_json/
    - assets/images/collection_icon/svg/
    - assets/images/qiblat_icon/svg/
    - assets/images/praying_time/svg/
    - assets/images/setting_icon/svg/
    - assets/images/error/lottie_json/
    - assets/images/permission/lottie_json/
    - assets/images/tasbih_icon/svg/
    - assets/images/dua_icon/svg/
    - assets/images/quran_icon/svg/
    - assets/images/image_of_the_day/
    - assets/sound/
    - assets/json/

  fonts:
    - family: Uthman
      fonts:
        - asset: assets/fonts/Uthman-Taha-Naskh-Regular.otf
        - asset: assets/fonts/Uthman-Taha-Naskh-Bold.otf
          weight: 700
    - family: Jameel
      fonts:
        - asset: assets/fonts/jameel.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
